### PR TITLE
Enforcing some code standards & optimizations

### PR DESCRIPTION
**Pull request by unquietwiki**
The add/change count on this is a bit deceptive; the binary files are "re-added" due to some git hiccup I can't immediately explain (but everything still works). The proposed changes will make it easier for others to build and make fixes on this.

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Hey! I really appreciate the initiative, but this is a bit much in one PR. There are a few things here I wouldn't really want to merge:

- electron-forge shouldn't be added as a standalone, this is a prior version
- yarn should probably not be added as a dependency that everyone installs
- I know that `prettier` isn't everyone's favorite, but it works well for me and I'd like to stick with it
- We _do_ need those assets!

I hate closing a PR, I know that feels terrible - but this is just a bit much change in one go.

**Comment by unquietwiki** [comment]
@felixrieseberg That's totally fine & understandable. Here was my thought process, if that helps...

- You can't compile the app without having **electron-forge** installed. There's no warning about it, and https://www.electronforge.io/ doesn't even hint you how to load it.
- I agree **yarn** should already be installed, but it wasn't on my fresh NodeJS 12.x LTS install; on a recently-reimaged Win10 Pro system. Your guess is as good as mine.
- The prior two things were supposed to be loading as dev-dependencies, not regular dependencies; users wouldn't encounter those.
- Could https://marketplace.visualstudio.com/items?itemName=numso.prettier-standard-vscode be a solution to the code-styling?
- The only assets I altered were the PNGs via optimization. Given the changes were largely 1 byte, I suspect some line-ending or byte-order-mark thing happened on the git pull. I'm using git version 2.27.0

**Comment by felixrieseberg** [comment]
electron-forge _is_ installed. You're just installing it again from a different version. Notice all the `@electron-forge` packages - those are the right ones.

**Comment by unquietwiki** [comment]
@felixrieseberg I see that now. (sigh) Well, I can revisit this by making sure Prettier is used, and verifying if byte-order-mark changes are being made, or not (I assume you're on a Mac).

**Pull request closed without merging**
